# Generated by Django 4.2.1 on 2023-11-24 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.IntegerField()),
                ("game_name", models.CharField(max_length=100)),
                (
                    "game_alternative_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "game_filename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("game_season", models.CharField(max_length=100)),
                ("game_home_team_score", models.IntegerField(blank=True, null=True)),
                ("game_away_team_score", models.IntegerField(blank=True, null=True)),
                ("game_round", models.IntegerField(blank=True, null=True)),
                ("game_spectators", models.IntegerField(blank=True, null=True)),
                (
                    "game_official",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("game_start_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "game_results",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("game_venue", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "game_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("game_city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "game_progress",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "game_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", exchange_app.models.GameStatus["SCHEDULED"]),
                            ("PLAYING", exchange_app.models.GameStatus["PLAYING"]),
                            ("FINISHED", exchange_app.models.GameStatus["FINISHED"]),
                            ("CANCELED", exchange_app.models.GameStatus["CANCELED"]),
                            ("POSTPONED", exchange_app.models.GameStatus["POSTPONED"]),
                            (
                                "ABDANDONED",
                                exchange_app.models.GameStatus["ABDANDONED"],
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("game_postponed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_id", models.IntegerField()),
                ("league_sport", models.CharField(max_length=100)),
                ("league_name", models.CharField(max_length=100)),
                ("league_alternative_name", models.CharField(max_length=100)),
                ("league_current_season", models.CharField(max_length=100)),
                ("league_formed_year", models.IntegerField()),
                ("league_first_event", models.CharField(max_length=100)),
                ("league_gender", models.CharField(max_length=100)),
                ("league_country", models.CharField(max_length=100)),
                ("league_description", models.CharField(max_length=5000)),
                ("league_badge", models.CharField(max_length=100)),
                ("league_logo", models.CharField(max_length=100)),
                ("league_trophy", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("LIMIT", "limit"), ("MARKET", "market")],
                        max_length=20,
                    ),
                ),
                (
                    "order_side",
                    models.CharField(
                        choices=[("BUY", "buy"), ("SELL", "sell")], max_length=20
                    ),
                ),
                (
                    "order_price",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                ("order_quantity", models.IntegerField(default=0)),
                ("order_filled_quantity", models.IntegerField(default=0)),
                ("order_working_quantity", models.IntegerField(default=0)),
                (
                    "order_avg_fill_price",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PARTIAL", "Partially Filled"),
                            ("FILLED", "Filled"),
                            ("CANCELED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "order_paid_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("order_creation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "order_modification_timestamp",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker_id", models.CharField(max_length=100)),
                (
                    "ticker_status",
                    models.CharField(
                        choices=[
                            ("OPEN", exchange_app.models.TickerStatus["OPEN"]),
                            ("CLOSED", exchange_app.models.TickerStatus["CLOSED"]),
                            ("CANCELED", exchange_app.models.TickerStatus["CANCELED"]),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "ticker_last_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ticker_best_bid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ticker_best_ask",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ticker_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ticker_maker_fee_pct",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=10),
                ),
                (
                    "ticker_taker_fee_pct",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                ("ticker_payout", models.IntegerField(default=10)),
                (
                    "ticker_outcome",
                    models.CharField(
                        choices=[
                            (
                                "LONGS_WIN",
                                exchange_app.models.TickerOutcome["LONGS_WIN"],
                            ),
                            (
                                "SHORTS_WIN",
                                exchange_app.models.TickerOutcome["SHORTS_WIN"],
                            ),
                            ("CANCELED", exchange_app.models.TickerOutcome["CANCELED"]),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ticker_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickers",
                        to="exchange_app.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_available_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user_locked_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_trade_id", models.CharField(max_length=20)),
                ("trade_quantity", models.PositiveIntegerField()),
                ("trade_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("trade_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "trade_buy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_trades",
                        to="exchange_app.order",
                    ),
                ),
                (
                    "trade_sell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_trades",
                        to="exchange_app.order",
                    ),
                ),
                (
                    "trade_ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField()),
                ("team_name", models.CharField(max_length=100)),
                (
                    "team_short_name",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("team_year_formed", models.IntegerField(blank=True, null=True)),
                ("team_sport", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "team_stadium",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "team_stadium_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("team_stadium_capacity", models.IntegerField(blank=True, null=True)),
                (
                    "team_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "team_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "team_gender",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "team_description",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("team_badge", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "team_jersey",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("team_logo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "team_league_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_league_1",
                        to="exchange_app.league",
                    ),
                ),
                (
                    "team_league_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_league_2",
                        to="exchange_app.league",
                    ),
                ),
                (
                    "team_league_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_league_3",
                        to="exchange_app.league",
                    ),
                ),
                (
                    "team_league_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_league_4",
                        to="exchange_app.league",
                    ),
                ),
                (
                    "team_league_5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_league_5",
                        to="exchange_app.league",
                    ),
                ),
                (
                    "team_league_6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_league_6",
                        to="exchange_app.league",
                    ),
                ),
                (
                    "team_league_7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_league_7",
                        to="exchange_app.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_quantity", models.IntegerField(default=0)),
                (
                    "position_average_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "position_open_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "position_closed_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "position_ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.ticker",
                    ),
                ),
                (
                    "position_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField()),
                ("player_name", models.CharField(max_length=50)),
                (
                    "player_sport",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "player_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("player_date_of_birth", models.DateTimeField(blank=True, null=True)),
                ("player_number", models.IntegerField(blank=True, null=True)),
                (
                    "player_birth_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "player_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "player_description",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "player_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "player_position",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "player_height",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "player_weight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "player_photo",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "player_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="order_ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exchange_app.ticker"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_games",
                to="exchange_app.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_games",
                to="exchange_app.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_games",
                to="exchange_app.league",
            ),
        ),
        migrations.CreateModel(
            name="Fill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fill_id", models.CharField(max_length=20)),
                (
                    "fill_side",
                    models.CharField(
                        choices=[("BUY", "buy"), ("SELL", "sell")], max_length=20
                    ),
                ),
                ("fill_quantity", models.PositiveIntegerField(default=0)),
                ("fill_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fill_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "fill_ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.ticker",
                    ),
                ),
                (
                    "fill_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
