# Generated by Django 4.2.1 on 2023-05-24 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.IntegerField()),
                ("sport", models.CharField(default="", max_length=100)),
                ("league", models.CharField(default="", max_length=100)),
                ("league_id", models.IntegerField(default=0)),
                ("home_team_score", models.IntegerField()),
                ("away_team_score", models.IntegerField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Open"),
                            ("PLAYING", "Partially Filled"),
                            ("FINISHED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("LIMIT", "limit"), ("MARKET", "market")],
                        max_length=20,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "buy"), ("SELL", "sell")], max_length=20
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField(default=0)),
                ("filled_quantity", models.IntegerField(default=0)),
                ("working_quantity", models.IntegerField(default=0)),
                (
                    "avg_fill_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PARTIAL", "Partially Filled"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paid_fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("modification_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("sport", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=100)),
                ("stadium", models.CharField(max_length=100)),
                ("badge", models.CharField(max_length=100)),
                ("jersey", models.CharField(max_length=100)),
                ("logo", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "maker_fee_pct",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=10),
                ),
                (
                    "taker_fee_pct",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickers",
                        to="exchange_app.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_id", models.CharField(max_length=20)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "buy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_trades",
                        to="exchange_app.order",
                    ),
                ),
                (
                    "sell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_trades",
                        to="exchange_app.order",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "average_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.ticker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField(default="")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exchange_app.ticker"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_games",
                to="exchange_app.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_games",
                to="exchange_app.team",
            ),
        ),
        migrations.CreateModel(
            name="Fill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fill_id", models.CharField(max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "buy"), ("SELL", "sell")], max_length=20
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.ticker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
