# Generated by Django 4.2.1 on 2023-11-27 01:22

from django.db import migrations, models
import exchange_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", exchange_app.models.GameStatus["SCHEDULED"]),
                    ("PLAYING", exchange_app.models.GameStatus["PLAYING"]),
                    ("FINISHED", exchange_app.models.GameStatus["FINISHED"]),
                    ("CANCELED", exchange_app.models.GameStatus["CANCELED"]),
                    ("POSTPONED", exchange_app.models.GameStatus["POSTPONED"]),
                    ("ABDANDONED", exchange_app.models.GameStatus["ABDANDONED"]),
                    ("NO_STATUS", exchange_app.models.GameStatus["NO_STATUS"]),
                ],
                max_length=20,
            ),
        ),
    ]
