# Generated by Django 4.2.1 on 2023-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="avg_fill_price",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(default="1", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_fees",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PARTIAL", "Partially Filled"),
                    ("FILLED", "Filled"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
