# Generated by Django 4.2.1 on 2023-05-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_app",
            "0002_alter_order_avg_fill_price_alter_order_order_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
