# Generated by Django 4.2.1 on 2023-05-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0003_alter_position_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Open"),
                    ("PLAYING", "Playing"),
                    ("FINISHED", "Finished"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
