# Generated by Django 4.2.1 on 2023-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0003_rename_trade_trade_id_trade_trade_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fill",
            name="fill_id",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PARTIAL", "Partially Filled"),
                    ("FILLED", "Filled"),
                    ("CANCELED", "Canceled"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
