# Generated by Django 4.2.1 on 2023-11-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0004_alter_fill_fill_id_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fill",
            name="fill_order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="exchange_app.order",
            ),
            preserve_default=False,
        ),
    ]
