# Generated by Django 4.2.1 on 2023-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0004_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="closed_pnl",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="position",
            name="open_pnl",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
