# Generated by Django 4.2.1 on 2023-05-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0005_position_closed_pnl_position_open_pnl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=100),
        ),
    ]
