# Generated by Django 4.2.1 on 2023-11-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0005_fill_fill_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fill",
            name="fill_ticker",
        ),
        migrations.RemoveField(
            model_name="fill",
            name="fill_user",
        ),
    ]
