# Generated by Django 4.2.1 on 2023-11-30 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exchange_app", "0006_remove_fill_fill_ticker_remove_fill_fill_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="fill",
            name="fill_ticker",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="exchange_app.ticker",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fill",
            name="fill_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fill",
            name="fill_id",
            field=models.CharField(max_length=20),
        ),
    ]
