# Generated by Django 4.2.1 on 2023-08-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0007_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="player_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
