# Generated by Django 4.2.1 on 2023-12-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0007_fill_fill_ticker_fill_fill_user_alter_fill_fill_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="position_settled_pnl",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PARTIAL", "Partially Filled"),
                    ("FILLED", "Filled"),
                    ("CANCELED", "Canceled"),
                    ("SETTLED", "Settled"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
