# Generated by Django 4.2.1 on 2023-08-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0008_player_player_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("PLAYING", "Playing"),
                    ("FINISHED", "Finished"),
                    ("CANCELLED", "Cancelled"),
                    ("POSTPONED", "Postponed"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
