# Generated by Django 4.2.1 on 2023-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0008_position_position_settled_pnl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="position_settled",
            field=models.BooleanField(default=False),
        ),
    ]
