# Generated by Django 4.2.1 on 2023-12-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0009_position_position_settled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_stadium_description",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
