# Generated by Django 4.2.1 on 2023-08-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0009_alter_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="away_team_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_team_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="number",
            field=models.IntegerField(null=True),
        ),
    ]
