# Generated by Django 4.2.1 on 2023-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0010_alter_team_team_stadium_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_height",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_nationality",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_photo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_position",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_sport",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_weight",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
