# Generated by Django 4.2.1 on 2023-08-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0012_alter_game_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="progress",
            field=models.CharField(default="", max_length=100),
        ),
    ]
