# Generated by Django 4.2.1 on 2023-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0013_alter_player_player_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_birth_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
