# Generated by Django 4.2.1 on 2023-08-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0013_game_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("CANCELED", "Canceled"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
