# Generated by Django 4.2.1 on 2023-08-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0014_alter_ticker_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
