# Generated by Django 4.2.1 on 2023-12-10 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exchange_app", "0015_alter_game_game_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", exchange_app.models.TransactionType["DEPOSIT"]),
                            (
                                "WITHDRAWAL",
                                exchange_app.models.TransactionType["WITHDRAWAL"],
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.IntegerField()),
                ("transaction_time", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                (
                    "transaction_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
