# Generated by Django 4.2.1 on 2023-08-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0016_ticker_payout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("PLAYING", "Playing"),
                    ("FINISHED", "Finished"),
                    ("CANCELLED", "Cancelled"),
                    ("POSTPONED", "Postponed"),
                    ("ABD", "Abd"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("CANCELED", "Canceled"),
                ],
                max_length=20,
            ),
        ),
    ]
