# Generated by Django 4.2.1 on 2023-08-30 21:24

from django.db import migrations, models
import exchange_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0017_alter_game_status_alter_ticker_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", exchange_app.models.MatchStatus["SCHEDULED"]),
                    ("PLAYING", exchange_app.models.MatchStatus["PLAYING"]),
                    ("FINISHED", exchange_app.models.MatchStatus["FINISHED"]),
                    ("CANCELLED", exchange_app.models.MatchStatus["CANCELLED"]),
                    ("POSTPONED", exchange_app.models.MatchStatus["POSTPONED"]),
                    ("ABD", exchange_app.models.MatchStatus["ABD"]),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", exchange_app.models.TickerStatus["OPEN"]),
                    ("CLOSED", exchange_app.models.TickerStatus["CLOSED"]),
                    ("CANCELED", exchange_app.models.TickerStatus["CANCELED"]),
                ],
                max_length=20,
            ),
        ),
    ]
