# Generated by Django 4.2.1 on 2023-12-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_app",
            "0018_rename_user_available_balance_userprofileinfo_user_total_balance_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticker",
            name="ticker_volume",
        ),
    ]
