# Generated by Django 4.2.1 on 2023-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_app",
            "0019_rename_balance_userprofileinfo_available_balance_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="fees_paid",
        ),
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="locked_balance",
        ),
        migrations.AddField(
            model_name="order",
            name="locked_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
