# Generated by Django 4.2.1 on 2023-12-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0020_remove_ticker_ticker_last_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fill",
            name="fill_id",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_id",
            field=models.CharField(max_length=50),
        ),
    ]
