# Generated by Django 4.2.1 on 2023-12-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0022_remove_position_position_open_pnl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticker",
            name="ticker_best_ask",
        ),
        migrations.RemoveField(
            model_name="ticker",
            name="ticker_best_bid",
        ),
    ]
