# Generated by Django 4.2.1 on 2023-12-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0023_remove_ticker_ticker_best_ask_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="user_total_balance",
        ),
    ]
