# Generated by Django 4.2.1 on 2024-01-16 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exchange_app", "0024_remove_userprofileinfo_user_total_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("login_ip", models.CharField(max_length=20)),
                (
                    "login_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("login_city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "login_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
